### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by TejasQ** [TejasQ/bookoid#3]
I'd like to use [Hasura cloud](https://hasura.io/) for the backend because it supports auth and gives us GraphQL on Postgres out of the box. Let's set this up.

**Comment by pavanmehta91** [comment]
Would you use a graphql client with this then? Like apollo/relay or uqrl etc?

**Comment by TejasQ** [comment]
I’ve never used Relay or Urql so it would be cool for me to learn those. We could also try swr. 

I have no opinion on what we use. 

You choose!

**Comment by TejasQ** [comment]
Closing because this is now done in https://github.com/TejasQ/bookoid/issues/7#issuecomment-696660210. Let's open a separate issue for client-side GraphQL integration.
